### PR TITLE
feat(doc): add Web Types

### LINKED ISSUE #1300: feat: add Web Types
### Describe Problem

To improve developers experience in WebStorm and other JetBrains IDEs, `ionicons` library can provide a Web-Types JSON file, which contains metadata of the library's Web Components. Developers will benefit from a code completion for attribute names and for icons:
list of icons

### Describe Preferred Solution

This issue will be followed by a PR to include Web Types JSON generation in the build and its distribution with the library.

### Describe Alternatives

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by piotrtomiak**
resolves #1300

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Hey there! Thanks for making this PR. Could you please describe what this feature does?

**Comment by piotrtomiak** [comment]
Hmm. I've created an issue - #1300, but it didn't link through the commit message. Details there.

**Comment by liamdebeasi** [comment]
Oh right, you added support for this to Ionic Vue as well. I knew your profile picture looked familiar 😄 

I'll have someone from the team review this week.

**Review by liamdebeasi — APPROVED** [review]
Thank you!

**Comment by liamdebeasi** [comment]
Merged. Thank you for contributing this!

**Comment by piotrtomiak** [comment]
Thanks!

**Pull request merged**
