### PR TITLE
fix(icon): allow svg stroke to be passed in

### PR DESCRIPTION
**Pull request by btsiders**
Related to https://github.com/ionic-team/ionic/issues/16483.

@brane53 asked that the stroke not be set at all, but I think setting it via a CSS var gives the most flexibility.

### CODE REVIEW

**Comment by ZachMoreno** [comment]
+1

**Comment by TomBourretViv** [comment]
Is there any news for this pull request ? I didn't find any solution to remove the default 'stroke' on my custom icons...

**Comment by FernandWTF** [comment]
I haven't find a way to remove the magic stroke as well. Would be cool if someone could look around at this PR please.

**Comment by btsiders** [comment]
I have no idea what happened to the code since the initial PR, but I have fixed it back up to not have any conflicts again.

**Comment by anagstef** [comment]
The way @btsiders implemented this does not introduce any breaking changes, but being able to turn `stroke` off is much needed. I think it should be merged.

**Comment by steebchen** [comment]
Can somebody please merge this? This is a must have for custom icons as it seems most of them are displayed incorrectly.

**Comment by anagstef** [comment]
@brandyscarney @liamdebeasi hey, i'm tagging you, cause maybe you have missed this Pull Request. It's a really important fix for custom icons. :)

**Comment by brandyscarney** [comment]
Thanks so much for the PR! I fixed this a little different, in the PR here: https://github.com/ionic-team/ionicons/pull/688

Basically I removed stroke entirely since it shouldn't be there even for `ionicons`, and moved the `fill` to the host element which allows developers to override them without any variables:

```
ion-icon {
  stroke: blue;
  fill: red;
}
```

I've released a dev build for this in Ionic, see my comment here: https://github.com/ionic-team/ionic/issues/16483#issuecomment-491336211

Please comment on that issue if you see any problems, thanks again!!

**Pull request closed without merging**
