### PR TITLE
Web Performance Improvement

### PR DESCRIPTION
**Pull request by DareBoost**
Better ordering the fonts src allows to browsers that support woff to use it rather than ttf (much heavier). It will save a lot of bandwith and faster the UX!

### CODE REVIEW

**Comment by jpalomar** [comment]
my pull request is a duplicate of this pull request: https://github.com/driftyco/ionicons/pull/218

:+1:

**Comment by skywong23** [comment]
#218

**Comment by julienbenisty** [comment]
did some quick test and I must say that it seems to be a good approach.
It's loading the woff file when supported which is only 66.7kb instead of loading the ttf file which is 185kb. Which is almost 3 times lighter. And that is with the full and default font files. It gets better once you remove unused icons.

+1 for me

**Comment by VladShcherbin** [comment]
+1

**Comment by alejandroiglesias** [comment]
I would say merge #218 and since this has conflicts.

**Comment by liamdebeasi** [comment]
Hey there,

We appreciate you contributing to Ionicons, and apologies for the delay! With Ionicons v5 we shifted our focus to SVGs. As a result, we no longer ship an icon font. I am going to close this, but let me know if you have questions.

**Pull request closed without merging**
