### PR TITLE
Added package.json so it can be published on NPM for use with webpack/browserify

### PR DESCRIPTION
**Pull request by IjzerenHein**
Hi, could you be so kind to publish this awesome package on NPM as well? There are more and more folks using bundlers like webpack and browserify and it would be awesome if this was on npm as well.

Regards, Hein

### CODE REVIEW

**Comment by jacobmarshall** [comment]
:+1:

**Comment by gabel** [comment]
:+1: Yes please

**Comment by gabel** [comment]
I've published a "-pre" package until this PR is merged... webpack ftw.
```
npm install ionicons-pre
```

**Comment by alexanderGugel** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: 

Is there an update on this? Would be great to have this merged.

**Comment by juanpablocs** [comment]
webpack integration?

**Comment by prismm** [comment]
yes, or documentation for use with webpack?

**Comment by nicknish** [comment]
I would love an NPM package to simplify adding ionicons to new projects. 

In the meantime here's how I got it working with webpack, JS, and Sass:

1.  I followed the instructions in the [**Getting Started**](https://github.com/ionic-team/ionicons#getting-started) section. If using Sass, be sure to use the `scss` files. Ensure all the filepaths are correct and update the variables.
2. Import the `ionicons.scss` into your app's main Sass file.
3. Add [`file-loader`](https://github.com/webpack-contrib/file-loader) package.
4. Add the webpack module rule:

```javascript
{ test: /\.(eot|woff|woff2|svg|ttf)([\?]?.*)$/, loader: "file-loader" }
```

You'll be good to use ionicons in your compiled JS now. Hope this helps, let me know if you have questions.

**Comment by amandaejohnston** [comment]
Thank you for the PR! Apologies for the... delay, haha. Ionicons has since been updated and published on npm: https://www.npmjs.com/package/ionicons I'll go ahead and close this out.

**Pull request closed without merging**
